### get all notes
GET http://localhost:3001/api/notes HTTP/1.1


### get one notes
GET http://localhost:3001/api/notes/1 HTTP/1.1

### POST new note 
POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
	"tittle":"primera nota en el sevidor",
	"content":"nota en el servidor"
}
